-- Set measurement_type for existing exercises based on their nature

-- DURATION: foam rolls, static holds, carries, breathing, cardio drills, static stretches
UPDATE exercises SET measurement_type = 'duration' WHERE slug IN (
    -- Foam rolling
    'thoracic_foam_roll',
    'lat_foam_roll',
    'quad_foam_roll',
    'hamstring_foam_roll',
    'it_band_foam_roll',
    'glute_foam_roll',
    'calf_foam_roll',
    'hip_flexor_foam_roll',
    'upper_back_foam_roll',

    -- CARs (Controlled Articular Rotations)
    'hip_cars',
    'shoulder_cars',
    'ankle_cars',
    'thoracic_cars',
    'wrist_cars',
    'neck_cars',

    -- Dynamic mobility flows (time-based)
    'arm_circle',
    'leg_swing_front_to_back',
    'leg_swing_side_to_side',
    'cat_cow_stretch',
    'worlds_greatest_stretch',
    'yoga_sun_salutation',
    'thread_the_needle',

    -- Static stretches
    'hip_90_90_stretch',
    'hip_flexor_lunge_stretch',
    'standing_quad_stretch',
    'standing_calf_stretch',
    'doorway_chest_stretch',
    'kneeling_adductor_stretch',
    'seated_piriformis_stretch',
    'childs_pose',
    'supine_twist',
    'upper_trap_stretch',
    'standing_hamstring_stretch',
    'pigeon_pose',
    'couch_stretch',
    'figure_four_stretch',
    'overhead_lat_stretch',
    'cross_body_shoulder_stretch',

    -- Isometric holds
    'wall_sit',
    'hollow_body_hold',
    'superman_hold',
    'copenhagen_plank',
    'isometric_mid_thigh_pull',
    'plank',
    'side_plank',
    'reverse_plank',
    'l_sit',
    'dead_hang',
    'active_hang',

    -- Carries (distance or duration — duration fits better for gym context)
    'farmers_walk',
    'suitcase_carry',
    'overhead_carry',
    'waiters_walk',
    'yoke_carry',

    -- Breathing & recovery
    'diaphragmatic_breathing',
    'box_breathing',
    '4_7_8_breathing',
    'nasal_breathing_drill',

    -- Cardio / continuous-effort drills
    'high_knees',
    'butt_kicks',
    'sprint_in_place',
    'mountain_climber',
    'lateral_shuffle',
    'shadow_boxing',
    'jumping_jacks',
    'jump_rope_standard',
    'jump_rope_double_under',
    'bear_crawl',
    'inchworm',
    'crab_walk',
    'duck_walk',
    'lateral_band_walk',
    'monster_walk',

    -- Low-intensity steady-state
    'bike_warmup',
    'treadmill_walk',
    'row_warmup',
    'elliptical_warmup'
);

-- DISTANCE: sprints, sled work, distance-based runs
UPDATE exercises SET measurement_type = 'distance' WHERE slug IN (
    'sprint_10m',
    'sprint_30m',
    'sprint_10m_flying',
    'flying_20_sprint',
    'acceleration_sprint_10m',
    'agility_505',
    'resisted_sprint',
    'sprint_parachute_run',
    'banded_sprint_resistance_run',
    'sprint_start_blocks',
    'stair_sprint',
    'prowler_push_sprint',
    'sled_push',
    'sled_pull',
    'sled_drag',
    'broad_jump_series',
    'agility_run',
    't_test_run',
    'pro_agility_run',
    '10_5_5_run',
    'shuttle_run'
);

-- REPS: strength, plyometrics, medicine ball, most accessory work
UPDATE exercises SET measurement_type = 'reps' WHERE slug IN (
    -- Squat pattern
    'back_squat',
    'front_squat',
    'goblet_squat',
    'box_squat',
    'pause_squat',
    'split_squat',
    'bulgarian_split_squat',
    'hack_squat',
    'zercher_squat',
    'overhead_squat',
    'pistol_squat',
    'single_leg_squat',
    'leg_press',
    'leg_extension',
    'leg_curl',

    -- Hinge pattern
    'romanian_deadlift',
    'conventional_deadlift',
    'sumo_deadlift',
    'trap_bar_deadlift',
    'single_leg_rdl',
    'good_morning',
    'hip_thrust',
    'glute_bridge',
    'single_leg_hip_thrust',
    'nordic_hamstring_curl',
    'glute_ham_raise',
    'reverse_hyper',

    -- Push pattern (upper)
    'bench_press',
    'incline_bench_press',
    'decline_bench_press',
    'dumbbell_bench_press',
    'push_up',
    'close_grip_bench_press',
    'overhead_press',
    'dumbbell_shoulder_press',
    'arnold_press',
    'lateral_raise',
    'front_raise',
    'cable_fly',
    'pec_deck',
    'tricep_pushdown',
    'skull_crusher',
    'dips',
    'pike_push_up',
    'diamond_push_up',
    'archer_push_up',

    -- Pull pattern (upper)
    'pull_up',
    'chin_up',
    'lat_pulldown',
    'seated_cable_row',
    'bent_over_row',
    'dumbbell_row',
    'face_pull',
    'band_pull_apart',
    'bicep_curl',
    'hammer_curl',
    'reverse_curl',
    'shrug',
    'upright_row',
    'rear_delt_fly',
    't_bar_row',
    'inverted_row',

    -- Core (reps-based)
    'crunch',
    'sit_up',
    'leg_raise',
    'hanging_leg_raise',
    'v_up',
    'toe_touch',
    'russian_twist',
    'bicycle_crunch',
    'ab_wheel_rollout',
    'cable_crunch',
    'pallof_press',
    'wood_chop',
    'dead_bug',
    'bird_dog',

    -- Plyometrics (reps-based)
    'box_jump',
    'depth_jump',
    'broad_jump',
    'vertical_jump',
    'lateral_bounds',
    'hurdle_hops',
    'jump_squat',
    'split_jump',
    'tuck_jump',
    'single_leg_hop',
    'reactive_drop_jump',
    'ankle_bounce',
    'drop_catch',
    'skater_jump',
    'medball_slam',
    'medball_rotational_throw',
    'medball_chest_pass',
    'medball_overhead_throw',
    'medball_scoop_toss',
    'clap_push_up',
    'medicine_ball_push_up',
    'medicine_ball_squat_throw',
    'kettlebell_swing',
    'kettlebell_clean',
    'kettlebell_snatch',
    'kettlebell_goblet_squat',

    -- Stability / accessory (reps-based)
    'clamshell',
    'fire_hydrant',
    'donkey_kick',
    'hip_abduction_machine',
    'hip_adduction_machine',
    'cable_hip_abduction',
    'banded_clamshell',
    'banded_hip_thrust',
    'terminal_knee_extension',
    'step_up',
    'reverse_lunge',
    'walking_lunge',
    'lateral_lunge',
    'curtsy_lunge',
    'glute_kickback',
    'prone_hip_extension',
    'seated_calf_raise',
    'standing_calf_raise',
    'ankle_dorsiflexion_drill',
    'wrist_roller',
    'grip_squeeze',
    'finger_extension',
    'scapular_push_up',
    'scapular_pull_up',
    'wall_slide',
    'external_rotation',
    'internal_rotation',
    'y_t_w_exercise',
    'prone_cobra',
    'back_extension',
    'reverse_back_extension',

    -- Sprint drills (reps of short efforts)
    'sprint_build_up',
    'sprint_acceleration',
    'sprint_deceleration',
    'sprint_curve',
    'change_of_direction_drill',
    'reactive_agility_drill',
    '5_10_5_drill',
    'L_drill',
    'star_drill'
);
