-- Add German descriptions to exercises
UPDATE exercises AS ex
SET description_i18n = description_i18n || v.de_patch
FROM (VALUES
    ('back_squat',            jsonb_build_object('de', 'Kniebeuge mit Langhantel auf dem Nacken. Primäre Kraftübung für den Unterkörper.')),
    ('front_squat',           jsonb_build_object('de', 'Kniebeuge mit Langhantel auf den Vorderdeltamuskeln. Höhere Anforderungen an Rumpfstabilität und Brustwirbelsäulenbeweglichkeit.')),
    ('romanian_deadlift',     jsonb_build_object('de', 'Hüftscharnierübung mit Langhantel. Primäre Kraftübung für Hamstrings und Gesäß.')),
    ('hip_thrust',            jsonb_build_object('de', 'Hüftstreckung mit Langhantel. Isoliert die Gesäßkraft im vollen Bewegungsumfang.')),
    ('bench_press',           jsonb_build_object('de', 'Horizontales Drücken mit Langhantel. Primäre Drückübung für den Oberkörper.')),
    ('incline_bench_press',   jsonb_build_object('de', 'Langhanteldrücken auf 30–45°-Schrägbank. Zielt auf obere Brust und vorderen Deltamuskel ab.')),
    ('pull_up',               jsonb_build_object('de', 'Klimmzug im Obergriff. Primäre vertikale Zugübung.')),
    ('chin_up',               jsonb_build_object('de', 'Klimmzug im Untergriff. Stärkere Bizepsbeteiligung als beim normalen Klimmzug.')),
    ('dips',                  jsonb_build_object('de', 'Körpergewichtsübung an den Dip-Barren. Trainiert Brust, Trizeps und vorderen Deltamuskel.')),
    ('push_up',               jsonb_build_object('de', 'Horizontale Drückübung mit Körpergewicht. Skalierbare Kraft- und Konditionsübung.')),
    ('bulgarian_split_squat', jsonb_build_object('de', 'Einbeinige Kniebeuge mit erhöhtem hinteren Fuß. Hohe Anforderungen an Quadrizeps und Gesäß.')),
    ('nordic_curl',           jsonb_build_object('de', 'Exzentrische Hamstringübung. Sehr effektiv zur Verletzungsprävention.')),
    ('box_jump',              jsonb_build_object('de', 'Explosiver Sprung auf eine Box. Entwickelt reaktive und konzentrische Kraft im Unterkörper.')),
    ('depth_jump',            jsonb_build_object('de', 'Von der Box steigen und sofort vertikal springen. Entwickelt reaktive Kraft.')),
    ('broad_jump',            jsonb_build_object('de', 'Maximaler horizontaler Sprung aus dem Stand. Testet die Leistungsabgabe des Unterkörpers.')),
    ('vertical_jump',         jsonb_build_object('de', 'Maximaler vertikaler Sprung aus dem Stand. Standardmaß für Unterkörperkraft.')),
    ('single_leg_box_jump',   jsonb_build_object('de', 'Einbeiniger explosiver Sprung auf eine Box. Hohe Anforderungen an Balance und Beinkraft.')),
    ('sprint_10m',            jsonb_build_object('de', 'Maximaler Beschleunigungssprint über 10 Meter. Testet explosive Startschnelligkeit.')),
    ('sprint_30m',            jsonb_build_object('de', 'Maximaler Sprint über 30 Meter. Testet Beschleunigung und Topspeedentwicklung.')),
    ('sprint_10m_flying',     jsonb_build_object('de', '10-Meter-Sprint mit fliegendem Start. Isoliert die reine Topgeschwindigkeit.')),
    ('agility_505',           jsonb_build_object('de', '5-Meter-Sprint, 180°-Wende, 5 Meter zurück. Standardtest für Richtungswechsel.')),
    ('mb_chest_throw',        jsonb_build_object('de', 'Zweihandiger Medizinballwurf von der Brust. Testet horizontale Oberkörperkraft.')),
    ('mb_overhead_throw',     jsonb_build_object('de', 'Zweihandiger Medizinballwurf über dem Kopf. Testet den gesamten Körperkrafttransfer.')),
    ('mb_rotational_throw',   jsonb_build_object('de', 'Rotationswurf des Medizinballs gegen eine Wand. Testet Rotationskraft.')),
    ('clap_push_up',          jsonb_build_object('de', 'Explosiver Liegestütz mit Handklatscher am oberen Punkt. Testet reaktive Oberkörperkraft.')),
      -- ── Jump Power ───────────────────────────────────────────────────────────
    ('lateral_bounds',          jsonb_build_object('de', 'Seitliche Einbeinsprünge zur Entwicklung lateraler Kraft und Kniestabilität.')),
    ('hurdle_hops',             jsonb_build_object('de', 'Kontinuierliche beidbeinige Sprünge über Mini-Hürden zur Entwicklung elastischer Steifigkeit und reaktiver Kraft.')),
    ('drop_jump',               jsonb_build_object('de', 'Von Boxhöhe fallen und sofort maximal springen – maximiert den reaktiven Kraftindex.')),
    ('pogos',                   jsonb_build_object('de', 'Schnelle, steifbeinige Sprünge auf den Fußballen zur Entwicklung reaktiver Sprunggelenkssteifigkeit.')),
    ('lateral_hurdle_hop',      jsonb_build_object('de', 'Kontinuierliche seitliche Einbeinsprünge über Mini-Hürden zur Entwicklung frontaler reaktiver Kraft.')),
    ('jump_squat',              jsonb_build_object('de', 'Explosiver Kniebeugesprung zur Entwicklung von Unterkörperkraft und reaktiver Stärke.')),
    ('squat_jump_to_stick',     jsonb_build_object('de', 'Explosiver Kniebeugesprung mit kontrollierter Landung – trainiert Landungsmechanik und Kraftentwicklung.')),

    -- ── Lower Body Explosivity ───────────────────────────────────────────────
    ('sled_push',                    jsonb_build_object('de', 'Explosiver Schlittenstoß zur Entwicklung horizontaler Kraft und sprintspezifischer Beinstreckung.')),
    ('sled_pull',                    jsonb_build_object('de', 'Rückwärts gezogener Widerstandsschlitten zur Entwicklung von Hüftbeuger- und Quadrizepskraft.')),
    ('resisted_sprint',              jsonb_build_object('de', 'Sprint mit Schlittenwiderstand zur Überlastung der Beschleunigungsmechanik und horizontalen Kraftentwicklung.')),
    ('sprint_parachute_run',         jsonb_build_object('de', 'Sprint mit Bremsschirm zur Entwicklung horizontaler Kraft bei hoher Geschwindigkeit.')),
    ('flying_20_sprint',             jsonb_build_object('de', 'Maximaler Geschwindigkeitssprint mit fliegendem Start zur Entwicklung der Topgeschwindigkeit.')),
    ('acceleration_sprint_10m',      jsonb_build_object('de', 'Kurzer Maximalsprint zur Entwicklung explosiver Beschleunigung und Antrittsschnelligkeit.')),
    ('prowler_push_sprint',          jsonb_build_object('de', 'Maximale Sprinttempo-Schlittendrückung für Kraftausdauer.')),
    ('sprint_start_blocks',          jsonb_build_object('de', 'Startblockstart zur Entwicklung explosiver Anfangsbeschleunigung und Antriebsphasenmechanik.')),
    ('a_skip_drill',                 jsonb_build_object('de', 'Kniehebe-Skipping zur Automatisierung der Sprintmechanik und des richtigen Fußaufsatzes.')),
    ('b_skip_drill',                 jsonb_build_object('de', 'Streckphasen-Sprintdrill zur Reinforcierung der Hamstring-Kursführung und Abdruckmechanik.')),
    ('high_knees',                   jsonb_build_object('de', 'Knieheben auf der Stelle zur Entwicklung von Hüftbeuger-Kraft und Sprintfrequenz.')),
    ('butt_kicks',                   jsonb_build_object('de', 'Schnelle Ferse-zu-Gesäß-Laufdrill zur Reinforcierung der Hamstringschnappbewegung und Sprintmechanik.')),
    ('wall_drill_march',             jsonb_build_object('de', 'Stehender Sprintdrill an der Wand zur Perfektionierung der Hüftmechanik und des Kniezugs.')),
    ('banded_hip_flexor_march',      jsonb_build_object('de', 'Widerstands-Hüftbeugermarsch zur Entwicklung von Hüftbeuger-Kraft und Schrittfrequenz.')),
    ('agility_ladder_ickey_shuffle', jsonb_build_object('de', 'Seitlicher Shuffle in der Agilitätsleiter zur Entwicklung von Fußgeschwindigkeit und Koordination.')),
    ('agility_ladder_single_leg_hops',jsonb_build_object('de', 'Einbeinige Sprünge durch die Agilitätsleiter zur Entwicklung reaktiver Fußkontakte und Balance.')),
    ('pro_agility_shuttle',          jsonb_build_object('de', 'Klassischer NFL-Combine-Drill mit schneller Verzögerung und Wiederbeschleunigung für laterale Schnelligkeit.')),
    ('t_drill',                      jsonb_build_object('de', 'Multidirektionaler Agilitätsdrill aus Vorwärtssprint und lateralem Shuffle für Richtungswechsel.')),
    ('reactive_drop_catch',          jsonb_build_object('de', 'Partner lässt Ball fallen – Athlet reagiert und fängt ihn vor dem zweiten Aufprall. Trainiert Reaktionsgeschwindigkeit.')),
    ('jump_rope_standard',           jsonb_build_object('de', 'Kontinuierliches Seilspringen zur Entwicklung von Sprunggelenkssteifigkeit und kardiovaskulärer Fitness.')),
    ('jump_rope_double_under',       jsonb_build_object('de', 'Zwei Seilumschläge pro Sprung zur Entwicklung explosiver Wadenpower und Koordination.')),
    ('burpee',                       jsonb_build_object('de', 'Ganzkörperbewegung von Boden zu Stand – kombiniert Kraft- und Konditionsanforderungen.')),
    ('burpee_broad_jump',            jsonb_build_object('de', 'Burpee mit explosivem Weitsprung für maximale Kraftentwicklung und Konditionierung.')),
    ('bear_crawl',                   jsonb_build_object('de', 'Vierfüßler-Vorwärtskriechen zur Entwicklung von Schulterstabilität, Rumpfkraft und Koordination.')),
    ('lateral_shuffle',              jsonb_build_object('de', 'Seitlicher athletischer Shuffle zur Entwicklung lateraler Schnelligkeit und Hüftabduktor-Ausdauer.')),
    ('shadow_boxing',                jsonb_build_object('de', 'Kontinuierliche Schlagkombinationen zur Entwicklung von Oberkörperausdauer und Koordination.')),
    ('jumping_jacks',                jsonb_build_object('de', 'Ganzkörpersprungbewegung zur Herzfrequenzerhöhung und Koordination der Gliedmaßen.')),
    ('star_jump',                    jsonb_build_object('de', 'Explosiver Hampelmann-Variante mit weitem Arm- und Beineinsatz auf dem Höhepunkt.')),
    ('sprint_in_place',              jsonb_build_object('de', 'Maximaler Beinumsatz auf der Stelle zur Entwicklung von Sprintfrequenz und Hüftbeuger-Geschwindigkeit.')),
    ('stair_sprint',                 jsonb_build_object('de', 'Explosiver Treppensprint zur Entwicklung von Unterkörperkraft und kardiovaskulärer Kapazität.')),
    ('banded_sprint_resistance_run', jsonb_build_object('de', 'Laufen mit Widerstandsband um die Hüfte für resisted Beschleunigungstraining zu Hause oder im Freien.')),
    ('dumbbell_snatch',              jsonb_build_object('de', 'Einarmiger explosiver Zug vom Boden über den Kopf zur Entwicklung unilateraler Kraftentwicklung.')),
    ('dumbbell_clean',               jsonb_build_object('de', 'Einarmiger oder beidarmiger Dumbbell-Clean zur Entwicklung explosiver Zugkraft ohne Langhantel.')),
    ('dumbbell_swing',               jsonb_build_object('de', 'Kettlebell-artiger Hüftscharnierschwung mit Kurzhantel zur Entwicklung der posterioren Kette.')),

    -- ── Mobility ─────────────────────────────────────────────────────────────
    ('worlds_greatest_stretch',       jsonb_build_object('de', 'Multigenlenk-Mobilitätsdrill kombiniert Hüftbeuger- und Brustwirbelsäulenmobilität in einer dynamischen Sequenz.')),
    ('hip_cars',                      jsonb_build_object('de', 'Vollständige aktive Hüftkreisrotationen zur Erhaltung der Hüftgelenkgesundheit und Endbereichskontrolle.')),
    ('shoulder_cars',                 jsonb_build_object('de', 'Kontrollierte Schulterrotationen durch den vollen Bewegungsumfang zur Erhaltung der Gelenkintegrität.')),
    ('ankle_cars',                    jsonb_build_object('de', 'Langsame kreisförmige Sprunggelenksrotationen zur Verbesserung der Sprunggelenksmobilität und Gelenkgesundheit.')),
    ('banded_ankle_distraction',      jsonb_build_object('de', 'Bandunterstützte Sprunggelenks-Dorsalflexionsmobilisation zur Verbesserung der Kniebeugetiefe und Sprintmechanik.')),
    ('hip_90_90_stretch',             jsonb_build_object('de', 'Sitzende Hüftmobilitätsübung zur Verbesserung der inneren und äußeren Hüftrotation für athletische Bewegungen.')),
    ('hip_flexor_lunge_stretch',      jsonb_build_object('de', 'Kniende Ausfallschrittposition zur Dehnung von Hüftbeugern und Psoas – kritisch für Sprintmechanik.')),
    ('leg_swing_front_to_back',       jsonb_build_object('de', 'Dynamische Hüftbeuge- und Streckungsschwünge zur Vorbereitung der Hamstrings auf Sprints.')),
    ('leg_swing_side_to_side',        jsonb_build_object('de', 'Laterale Hüftschwünge zur Mobilisierung der Hüftabduktoren und -adduktoren vor seitlichen Sportbewegungen.')),
    ('arm_circle',                    jsonb_build_object('de', 'Schultergelenk-Mobilisierungsaufwärmübung zur Vorbereitung der Rotatorenmanschette vor Drück- oder Wurfbewegungen.')),
    ('standing_quad_stretch',         jsonb_build_object('de', 'Aufrechte Einbein-Quadrizepsdehnung zur Wiederherstellung der Oberschenkellänge nach dem Laufen oder Kniebeugen.')),
    ('kneeling_adductor_stretch',     jsonb_build_object('de', 'Leisten- und Oberschenkelinnendehnung für Adduktoren – wichtig für Sportler mit seitlichen Bewegungen.')),
    ('doorway_chest_stretch',         jsonb_build_object('de', 'Brust- und Schulterdehnung zur Korrektur der Drückmechanik und Verbesserung der Körperhaltung.')),
    ('thoracic_foam_roll',            jsonb_build_object('de', 'Wirbelsäulenstreckungsmobilisation über Schaumstoffrolle zur Verbesserung der Brustwirbelsäulenmobilität und Haltung.')),
    ('lat_foam_roll',                 jsonb_build_object('de', 'Seitliches Torsorolling zur Lösung von Lat-Verspannungen und Verbesserung der Schulterreichweite.')),
    ('quad_foam_roll',                jsonb_build_object('de', 'Oberschenkelrollen zur Reduzierung der Quadrizepsspannung vor und nach schwerem Training.')),
    ('hamstring_foam_roll',           jsonb_build_object('de', 'Oberschenkelrückseitenrolling zur Reduzierung von Muskelkater und Verbesserung der Gewebsqualität bei Sprintathleten.')),
    ('it_band_foam_roll',             jsonb_build_object('de', 'Seitliches Oberschenkelrolling zur Reduzierung der IT-Band-Spannung und lateraler Knieschmerzen.')),
    ('glute_foam_roll',               jsonb_build_object('de', 'Gesäß- und Piriformis-Rolling zur Lösung von Hüftrotatorenverspannungen vor oder nach dem Training.')),
    ('childs_pose',                   jsonb_build_object('de', 'Erholungsübung für Hüfte und Brustwirbelsäule zur Dekompression der Wirbelsäule und Beruhigung des Nervensystems.')),
    ('supine_twist',                  jsonb_build_object('de', 'Liegende Rotationsdehnung zur Lösung von Lendenwirbelsäulenspannungen nach dem Training.')),
    ('diaphragmatic_breathing',       jsonb_build_object('de', 'Langsames Bauchatmungsprotokoll zur Aktivierung des parasympathischen Nervensystems und Verbesserung der Erholung.')),
    ('box_breathing',                 jsonb_build_object('de', '4-4-4-4-Atemkontrolltechnik zur Reduzierung von Cortisol und Vorbereitung des ZNS auf Training oder Wettkampf.')),
    ('yoga_sun_salutation',           jsonb_build_object('de', 'Verbundene Körperhaltungssequenz zur Wiederherstellung der Flexibilität und Beruhigung des Nervensystems nach dem Training.')),
    ('cat_cow_stretch',               jsonb_build_object('de', 'Wirbelsäulenbeuge- und -streckungssequenz zur Mobilisierung der Brust- und Lendenwirbelsäule nach dem Training.')),
    ('thread_the_needle',             jsonb_build_object('de', 'Rotations-Schulter- und Brustwirbelsäulendehnung aus dem Vierfüßlerstand zur Verbesserung der Brustwirbelsäulenmobilität.')),
    ('prone_hip_internal_rotation',   jsonb_build_object('de', 'Bauchlagenknöchelrotation zur Verbesserung der Hüftinnenrotation, die durch Sitzen und Training verloren geht.')),
    ('standing_calf_stretch',         jsonb_build_object('de', 'Wandunterstützte Waden- und Achillessehnenstreckung zur Wiederherstellung der Dorsalflexion.')),
    ('seated_piriformis_stretch',     jsonb_build_object('de', 'Vier-Figur-Stretch für Piriformis und tiefe Hüftaußenrotatoren.')),
    ('upper_trap_stretch',            jsonb_build_object('de', 'Seitliche Nackeneigung zur Lösung von Schulterheber-Verspannungen, die durch das Training entstehen.')),
    ('wrist_mobility_circles',        jsonb_build_object('de', 'Kreisförmige Handgelenksrotationen und -streckungen zur Vorbereitung und Erholung der Handgelenke für Drückbewegungen.')),
    ('thoracic_extension_chair',      jsonb_build_object('de', 'Stuhlrückenlehne als Mobilisierungspunkt zur Wiederherstellung der Brustwirbelsäulenstreckung ohne Schaumstoffrolle.')),
    ('standing_spinal_rotation',      jsonb_build_object('de', 'Stehende Rumpfrotation zum Aufwärmen oder Lösen der thorakalen Rotation für athletische Bewegungen.')),
    ('neck_circles',                  jsonb_build_object('de', 'Kontrollierte Halsrotationen und seitliche Beugungen zur Lösung von Nackenverspannungen und Verbesserung der Mobilität.')),

    -- ── Strength ─────────────────────────────────────────────────────────────
    ('power_clean',               jsonb_build_object('de', 'Olympisches Hebezeug – Langhantel explosiv vom Boden in die Frontrack-Position zur Entwicklung der Ganzkörperkraft.')),
    ('hang_power_clean',          jsonb_build_object('de', 'Power-Clean aus der Mittelschenkelposition zur Betonung der explosiven Hüftstreckung und Kraftentwicklungsrate.')),
    ('power_snatch',              jsonb_build_object('de', 'Breitgriff-Langhantelzug vom Boden über den Kopf in einem Bewegungsablauf für explosive Ganzkörperkoordination.')),
    ('hang_power_snatch',         jsonb_build_object('de', 'Reißen aus der Mittelschenkelposition mit Fokus auf violente Hüftstreckung und Überkopfstabilität.')),
    ('push_press',                jsonb_build_object('de', 'Unterkörperantrieb zur Überkopf-Langhanteldrückung – verbindet Beinkraft mit Oberkörperkraft.')),
    ('trap_bar_deadlift',         jsonb_build_object('de', 'Kreuzheben mit Trapezstange zur Reduzierung der Wirbelsäulenbelastung bei maximaler Bein- und Hüftkraft.')),
    ('conventional_deadlift',     jsonb_build_object('de', 'Vollständiges Hüftscharnierziehen vom Boden zur Entwicklung der posterioren Kette und maximalen Kraftentwicklung.')),
    ('sumo_deadlift',             jsonb_build_object('de', 'Breitstandiges hüftdominantes Kreuzheben für Adduktoren und Gesäß – Stärke im Unterköper.')),
    ('stiff_leg_deadlift',        jsonb_build_object('de', 'Minimale Kniebeugung beim Hüftscharnier für maximale Hamstring-Beanspruchung durch den vollen Bewegungsumfang.')),
    ('reverse_lunge',             jsonb_build_object('de', 'Rückwärtsausfallschritt zur Reduzierung der Kniebelastung und Entwicklung der einbeinigen Kraft und Balance.')),
    ('nordic_hamstring_curl',     jsonb_build_object('de', 'Exzentrische Hamstringübung mit höchster Verletzungspräventionswirkung bei Hamstringzerrungen bei Sprintathleten.')),
    ('single_leg_calf_raise',     jsonb_build_object('de', 'Unilaterale Plantarflexion zur Entwicklung der Achillessehnenresilienz und Wadenstärke.')),
    ('tibialis_raise',            jsonb_build_object('de', 'Dorsalflexionsstärkung zur Vorbeugung von Schienbeinkantensyndrom und Unterstützung der Sprintmechanik.')),
    ('wall_sit',                  jsonb_build_object('de', 'Isometrisches Quadrizepshalten bei 90° zur Entwicklung der Beinausdauer und Sehnentoleranz.')),
    ('reverse_hyperextension',    jsonb_build_object('de', 'Hintere Kettensteckung auf der Reverse-Hyper-Maschine zur Dekompression der Wirbelsäule und Stärkung der Gesäßmuskeln.')),
    ('back_extension_45deg',      jsonb_build_object('de', 'Kontrollierte Hüftstreckung auf der 45°-Rückenstreckbank für Gesäß- und Hamstringausdauer.')),
    ('copenhagen_plank',          jsonb_build_object('de', 'Adduktoren-fokussierte Seitstützposition für Leistenkraft und Hüftstabilität in multidirektionalen Sportarten.')),
    ('incline_dumbbell_press',    jsonb_build_object('de', 'Schräges Kurzhanteldrcüken für obere Brust und Schulter-Stabilität für Überkopf-Athleten.')),
    ('landmine_press',            jsonb_build_object('de', 'Einarmiges Schrägdrücken aus der Landmine-Position zur Entwicklung der Schulterkraft mit reduziertem Impingementrisiko.')),
    ('weighted_pull_up',          jsonb_build_object('de', 'Klimmzug mit Zusatzgewicht zur Maximierung der Lat- und Oberkörperkraft.')),
    ('dumbbell_row',              jsonb_build_object('de', 'Unilaterales horizontales Ziehen zum Ausgleich von Kraftungleichgewichten und Aufbau der Latissimus- und mittleren Rückenmuskulatur.')),
    ('band_pull_apart',           jsonb_build_object('de', 'Horizontales Bandstrecken zur Aktivierung der Hinterdeltamuskeln und mittleren Rückenmuskulatur für Schultergesundheit.')),
    ('scapular_pull_up',          jsonb_build_object('de', 'Hängende Schulterblatt-Retraktion und -Depression zur Aktivierung der unteren Trapezmuskulatur und Schultergelenkschutz.')),
    ('dead_bug',                  jsonb_build_object('de', 'Kontralaterale Gliedmaßensteckung in Rückenlage zur Entwicklung der tiefen Rumpfstabilität und Koordination.')),
    ('bird_dog',                  jsonb_build_object('de', 'Vierfüßler-kontralaterale Streckung zur Entwicklung der Lendenstabilität und Hüftstreckungskontrolle.')),
    ('ab_wheel_rollout',          jsonb_build_object('de', 'Anti-Extensions-Rumpfübung mit dem Bauchroller zur Herausforderung der Wirbelsäulenstabilität am Endbereich.')),
    ('cable_chop',                jsonb_build_object('de', 'Rotationsmuster von oben nach unten zur Entwicklung athletischer Rumpfrotationsanforderungen.')),
    ('hanging_leg_raise',         jsonb_build_object('de', 'Hüftbeugung aus dem Hang zur Entwicklung der unteren Bauchmuskulatur und Hüftbeuger-Kraft.')),
    ('copenhagen_hip_adduction',  jsonb_build_object('de', 'Seitlicher Stütz mit oberem Bein auf der Bank zur Entwicklung der Adduktorenkraft und Reduzierung des Leistenrisikos.')),
    ('farmers_walk',              jsonb_build_object('de', 'Beidseitiger belasteter Tragen zur Entwicklung von Griffkraft und Rumpfstabilität unter realen Bewegungsanforderungen.')),
    ('suitcase_carry',            jsonb_build_object('de', 'Unilateraler belasteter Tragen zur Herausforderung der lateralen Rumpfstabilität und Hüftausrichtung.')),
    ('isometric_mid_thigh_pull',  jsonb_build_object('de', 'Maximaler isometrischer Zug gegen unbewegte Langhantel zur Entwicklung von Neuralantrieb und Spitzenkraft.')),
    ('single_leg_glute_bridge',   jsonb_build_object('de', 'Unilaterale Hüftstreckung vom Boden zur Verbesserung der Glutäusaktivierung und Hüftstabilität.')),
    ('banded_monster_walk',       jsonb_build_object('de', 'Laterales Widerstandsbandgehen zur Aktivierung der Hüftabduktoren und des Gluteus medius vor dem Beintraining.')),
    ('lateral_band_walk',         jsonb_build_object('de', 'Seitschritt mit Widerstandsband über den Knien zur Reinforcierung der Knieausrichtung und Abduktorenstärke.')),
    ('banded_clamshell',          jsonb_build_object('de', 'Seitliche Hüftaußenrotation gegen Widerstand zur Entwicklung des Gluteus medius und Reduzierung von Knievalgus.')),
    ('wide_grip_push_up',         jsonb_build_object('de', 'Weite Handposition für erhöhte Brustaktivierung und größeren Bewegungsumfang beim Liegestütz.')),
    ('diamond_push_up',           jsonb_build_object('de', 'Enger Trizeps-Liegestütz mit rautenförmig platzierten Händen unter der Brust.')),
    ('decline_push_up',           jsonb_build_object('de', 'Fußerhöhter Liegestütz zur Verlagerung der Last auf die obere Brust und den vorderen Deltamuskel.')),
    ('archer_push_up',            jsonb_build_object('de', 'Unilateral belasteter Liegestütz mit Gewichtsverlagerung auf einen Arm zur Entwicklung der Einarmstärke.')),
    ('pike_push_up',              jsonb_build_object('de', 'Abwärtshund-Liegestütz für Schultern als Progression zur Handstand-Überkopfpresse.')),
    ('shoulder_tap_push_up',      jsonb_build_object('de', 'Liegestütz mit alternierenden Schultertaps zur Entwicklung der Anti-Rotations-Rumpfstabilität.')),
    ('tricep_dip',                jsonb_build_object('de', 'Oberkörperdrückbewegung an parallelen Barren oder stabilen Stühlen – entwickelt Trizeps und Brust.')),
    ('negative_pull_up',          jsonb_build_object('de', 'Langsames exzentrisches Absenken vom Kinn über der Stange zur Entwicklung der Zugkraft für Anfänger.')),
    ('bodyweight_squat',          jsonb_build_object('de', 'Grundlegendes Kniebeugemuster ohne Last zur Entwicklung von Mobilität und Bewegungsqualität.')),
    ('pistol_squat',              jsonb_build_object('de', 'Einbeinige Tiefkniebeuge erfordert Kraft, Balance und Sprunggelenksmobilität.')),
    ('assisted_pistol_squat',     jsonb_build_object('de', 'Einbeinige Kniebeuge mit Halteunterstützung als Progression zur vollständigen Pistolkniebeuge.')),
    ('split_squat',               jsonb_build_object('de', 'Stationäre Ausfallschrittposition zur Entwicklung der einbeinigen Beinstreckung ohne Equipment.')),
    ('walking_lunge',             jsonb_build_object('de', 'Vorwärtsschrittausfallschritt zur Entwicklung von Einbein-Kraft und dynamischer Hüftstabilität.')),
    ('lateral_lunge',             jsonb_build_object('de', 'Seitwärtsausfallschritt zur Entwicklung der Adduktorenkraft und Hüftmobilität in der Frontalebene.')),
    ('wall_supported_hamstring_curl', jsonb_build_object('de', 'Bauchlage-Hüftstreckungscurl mit Wandverankerung zur Entwicklung der Hamstringkraft zu Hause.')),
    ('donkey_kick',               jsonb_build_object('de', 'Vierfüßler-Hüftstreckung zur Isolierung und Aktivierung des Gluteus maximus in einer heimfreundlichen Position.')),
    ('fire_hydrant',              jsonb_build_object('de', 'Vierfüßler-Hüftabduktion zur Aktivierung des Gluteus medius und Verbesserung der Hüftaußenrotation.')),
    ('standing_hip_abduction',    jsonb_build_object('de', 'Stehende seitliche Beinhebung zur Entwicklung der Hüftabduktorenstärke und Beckenstabilität.')),
    ('standing_hip_extension',    jsonb_build_object('de', 'Stehende Rückwärtsbeinhebung zur Aktivierung der Gesäßmuskeln und Reinforcierung der Hüftstreckungsmechanik.')),
    ('calf_raise_bilateral',      jsonb_build_object('de', 'Beidbeinige Fersenhebung zur Entwicklung von Waden- und Achillessehnen-Kraft und Ausdauer.')),
    ('sumo_squat',                jsonb_build_object('de', 'Breitstandige Körpergewichtskniebeuge für Innenoberschenkel und Gesäß mit aufrechtem Oberkörper.')),
    ('hollow_body_hold',          jsonb_build_object('de', 'Rückenlage-Ganzkörperspannungsposition zur Entwicklung des vorderen Rumpfes und Körperbewusstsein für athletische Bewegungen.')),
    ('v_up',                      jsonb_build_object('de', 'Vollständige Bauchpresse – Hände zu Füßen zur Entwicklung dynamischer Rumpfbeugekraft.')),
    ('reverse_crunch',            jsonb_build_object('de', 'Liegende Hüfthebung mit Knie zur Brust zur Entwicklung der unteren Bauchmuskulatur und Hüftbeuger-Kraft.')),
    ('bicycle_crunch',            jsonb_build_object('de', 'Abwechselnder Ellbogen-zu-Knie-Crunch zur Entwicklung der Schrägmuskel-Kraft und rotatorischen Rumpfstabilität.')),
    ('superman_hold',             jsonb_build_object('de', 'Bauchlage-gleichzeitige Gliedmaßenhebung zur Entwicklung der Rückenstrecker-Ausdauer und posterioren Kette.')),
    ('mountain_climber',          jsonb_build_object('de', 'Planken-Knieheben zur Entwicklung von Rumpfstabilität und kardiovaskulärer Konditionierung.')),
    ('spiderman_plank',           jsonb_build_object('de', 'Plank mit abwechselnden Knie-zu-Ellbogen-Drives für Rotationsstabilität und Hüftmobilität.')),
    ('toe_touch_crunch',          jsonb_build_object('de', 'Beinhebecrunch-Kombination zur Entwicklung der gesamten vorderen Rumpfkette.')),
    ('banded_squat',              jsonb_build_object('de', 'Körpergewichtskniebeuge mit Band über den Knien zur Knieausrichtung und Glutäusaktivierung.')),
    ('banded_hip_thrust',         jsonb_build_object('de', 'Gesäßbrücke mit Widerstandsband für progressive Überladung des Gluteus ohne Fitnessstudio.')),
    ('banded_romanian_deadlift',  jsonb_build_object('de', 'Hüftscharnierübung mit Band unterhalb des Fußes zur Entwicklung von Hamstring- und Gesäßkraft ohne Langhantel.')),
    ('banded_row',                jsonb_build_object('de', 'Horizontales Ziehen mit Widerstandsband (an Tür verankert) zur Entwicklung der Rückenmuskulatur zu Hause.')),
    ('banded_overhead_press',     jsonb_build_object('de', 'Vertikales Drücken stehend auf Band zur Entwicklung der Schulterkraft ohne Kurzhantel oder Langhantel.')),
    ('banded_lateral_raise',      jsonb_build_object('de', 'Seitliches Heben gegen Bandwiderstand zur Entwicklung des lateralen Deltamuskels und Schulter-Stabilität.')),
    ('banded_good_morning',       jsonb_build_object('de', 'Hüftscharnierübung mit Band für Aktivierung der posterioren Kette und Hamstring-Aufwärmung.')),
    ('banded_face_pull',          jsonb_build_object('de', 'Bandzug zum Gesicht (an Tür verankert) zur Stärkung der hinteren Deltamuskeln und Außenrotatoren zu Hause.')),
    ('banded_kickback',           jsonb_build_object('de', 'Hüftstreckung mit Band zur Gesäßisolierung und Aktivierung in einem heimfreundlichen Setting.')),
    ('banded_bicycle',            jsonb_build_object('de', 'Liegender Fahrrad-Crunch mit Widerstandsband für zusätzliche Rumpf- und Hüftbeuger-Herausforderung.')),
    ('banded_chest_press_floor',  jsonb_build_object('de', 'Bodendrücken mit Band (hinter dem Körper verankert) für Brusttraining ohne Bank oder Langhantel.')),
    ('dumbbell_thruster',         jsonb_build_object('de', 'Kniebeuge zu Überkopfpresse in einer Bewegung für Ganzkörperkonditionierung und Kraftentwicklung.')),
    ('dumbbell_rdl',              jsonb_build_object('de', 'Beidarmiges Hüftscharnier mit Kurzhanteln für Hamstrings und Gesäß ohne Langhantel.')),
    ('dumbbell_lateral_lunge',    jsonb_build_object('de', 'Seitwärtsausfallschritt mit Kurzhantel für zusätzlichen Widerstand in der frontalen Kraftentwicklung.')),
    ('dumbbell_step_up_to_press', jsonb_build_object('de', 'Aufstieg kombiniert mit Überkopfpresse zur Entwicklung einbeiniger Antriebskraft und Oberkörperstärke.')),
    ('dumbbell_curl_to_press',    jsonb_build_object('de', 'Bizepscurl zur Überkopfpresse – kombiniert Armkraft und Schulter-Stabilität.')),
    ('renegade_row',              jsonb_build_object('de', 'Liegestützposition mit abwechselnden Kurzhanteln ziehen – entwickelt Rücken und Anti-Rotations-Rumpfstabilität.')),
    ('dumbbell_floor_press',      jsonb_build_object('de', 'Brustdrücken liegend auf dem Boden zur Entwicklung der Drückkraft mit begrenzter Schulterstreckung.')),
    ('dumbbell_hip_hinge_row',    jsonb_build_object('de', 'Hüftscharnier-Position mit Kurzhantelzug für simultanes Training der posterioren Kette und des oberen Rückens.')),
    ('dumbbell_goblet_reverse_lunge', jsonb_build_object('de', 'Rückwärtsausfallschritt mit Kurzhantel auf Brusthöhe für zusätzliche Last und Rumpfstabilität.')),

    -- ── Upper Body Plyometrics ───────────────────────────────────────────────
    ('medicine_ball_slam',        jsonb_build_object('de', 'Überkopf-zu-Boden-Wurfbewegung zur Entwicklung der Rumpfkraft und explosiver Dreierkettensteckung.')),
    ('rotational_med_ball_throw', jsonb_build_object('de', 'Seitlicher Rotationswurf gegen Wand zur Entwicklung rotatorischer Kraft – übertragbar auf Sportbewegungen.')),
    ('med_ball_chest_pass',       jsonb_build_object('de', 'Explosiver beidarmiger Brustpass zur Entwicklung horizontaler Oberkörperdruckkraft.')),
    ('med_ball_overhead_throw',   jsonb_build_object('de', 'Beidarmiger Überkopfwurf vorwärts zur Entwicklung von Rumpf- und Hüftstreckungskraft.')),
    ('med_ball_scoop_toss',       jsonb_build_object('de', 'Schneller Aufwärtswurf durch Hüftstreckung – simuliert Sprungmechanik für sauberen Kraftübertrag.'))
) AS v(slug, de_patch)
WHERE ex.slug = v.slug;
