INSERT INTO sports (slug, group_name) VALUES
    ('boxing',       'combat_sports'),
    ('mma',          'combat_sports'),
    ('wrestling',    'combat_sports'),
    ('judo',         'combat_sports'),
    ('bjj',          'combat_sports'),
    ('kickboxing',   'combat_sports'),
    ('karate',       'combat_sports'),
    ('taekwondo',    'combat_sports'),
    ('football',     'team_sports'),
    ('basketball',   'team_sports'),
    ('volleyball',   'team_sports'),
    ('handball',     'team_sports'),
    ('rugby',        'team_sports'),
    ('hockey',       'team_sports'),
    ('soccer',       'team_sports'),
    ('sprinting',    'athletics'),
    ('jumping',      'athletics'),
    ('throwing',     'athletics'),
    ('powerlifting', 'strength'),
    ('weightlifting','strength'),
    ('crossfit',     'strength'),
    ('bodybuilding', 'strength'),
    ('running',      'endurance'),
    ('cycling',      'endurance'),
    ('swimming',     'endurance'),
    ('triathlon',    'endurance'),
    ('tennis',       'racket_sports'),
    ('badminton',    'racket_sports'),
    ('squash',       'racket_sports'),
    ('gymnastics',   'other'),
    ('climbing',     'other'),
    ('other',        'other')
ON CONFLICT DO NOTHING;

INSERT INTO sport_category_relevance (sport_id, category_id, relevance)
SELECT s.id, c.id, v.relevance
FROM (VALUES
    ('boxing',       'strength',               3),
    ('boxing',       'jumps',                  2),
    ('boxing',       'lower_body_plyometrics',  2),
    ('boxing',       'upper_body_plyometrics',  3),
    ('boxing',       'mobility',               3),
    ('mma',          'strength',               3),
    ('mma',          'jumps',                  2),
    ('mma',          'lower_body_plyometrics',  2),
    ('mma',          'upper_body_plyometrics',  3),
    ('mma',          'mobility',               3),
    ('wrestling',    'strength',               3),
    ('wrestling',    'jumps',                  1),
    ('wrestling',    'lower_body_plyometrics',  2),
    ('wrestling',    'upper_body_plyometrics',  2),
    ('wrestling',    'mobility',               3),
    ('judo',         'strength',               3),
    ('judo',         'jumps',                  1),
    ('judo',         'lower_body_plyometrics',  2),
    ('judo',         'upper_body_plyometrics',  2),
    ('judo',         'mobility',               3),
    ('bjj',          'strength',               3),
    ('bjj',          'jumps',                  1),
    ('bjj',          'lower_body_plyometrics',  1),
    ('bjj',          'upper_body_plyometrics',  2),
    ('bjj',          'mobility',               3),
    ('kickboxing',   'strength',               3),
    ('kickboxing',   'jumps',                  2),
    ('kickboxing',   'lower_body_plyometrics',  2),
    ('kickboxing',   'upper_body_plyometrics',  3),
    ('kickboxing',   'mobility',               3),
    ('karate',       'strength',               2),
    ('karate',       'jumps',                  2),
    ('karate',       'lower_body_plyometrics',  2),
    ('karate',       'upper_body_plyometrics',  3),
    ('karate',       'mobility',               3),
    ('taekwondo',    'strength',               2),
    ('taekwondo',    'jumps',                  3),
    ('taekwondo',    'lower_body_plyometrics',  3),
    ('taekwondo',    'upper_body_plyometrics',  2),
    ('taekwondo',    'mobility',               3),
    ('football',     'strength',               3),
    ('football',     'jumps',                  2),
    ('football',     'lower_body_plyometrics',  3),
    ('football',     'upper_body_plyometrics',  2),
    ('football',     'mobility',               2),
    ('basketball',   'strength',               2),
    ('basketball',   'jumps',                  3),
    ('basketball',   'lower_body_plyometrics',  3),
    ('basketball',   'upper_body_plyometrics',  2),
    ('basketball',   'mobility',               2),
    ('volleyball',   'strength',               2),
    ('volleyball',   'jumps',                  3),
    ('volleyball',   'lower_body_plyometrics',  2),
    ('volleyball',   'upper_body_plyometrics',  2),
    ('volleyball',   'mobility',               2),
    ('handball',     'strength',               2),
    ('handball',     'jumps',                  2),
    ('handball',     'lower_body_plyometrics',  3),
    ('handball',     'upper_body_plyometrics',  3),
    ('handball',     'mobility',               2),
    ('rugby',        'strength',               3),
    ('rugby',        'jumps',                  2),
    ('rugby',        'lower_body_plyometrics',  3),
    ('rugby',        'upper_body_plyometrics',  2),
    ('rugby',        'mobility',               2),
    ('hockey',       'strength',               2),
    ('hockey',       'jumps',                  2),
    ('hockey',       'lower_body_plyometrics',  3),
    ('hockey',       'upper_body_plyometrics',  1),
    ('hockey',       'mobility',               2),
    ('soccer',       'strength',               2),
    ('soccer',       'jumps',                  2),
    ('soccer',       'lower_body_plyometrics',  3),
    ('soccer',       'upper_body_plyometrics',  1),
    ('soccer',       'mobility',               2),
    ('sprinting',    'strength',               2),
    ('sprinting',    'jumps',                  2),
    ('sprinting',    'lower_body_plyometrics',  3),
    ('sprinting',    'upper_body_plyometrics',  1),
    ('sprinting',    'mobility',               3),
    ('jumping',      'strength',               2),
    ('jumping',      'jumps',                  3),
    ('jumping',      'lower_body_plyometrics',  3),
    ('jumping',      'upper_body_plyometrics',  1),
    ('jumping',      'mobility',               3),
    ('throwing',     'strength',               3),
    ('throwing',     'jumps',                  2),
    ('throwing',     'lower_body_plyometrics',  2),
    ('throwing',     'upper_body_plyometrics',  3),
    ('throwing',     'mobility',               3),
    ('powerlifting', 'strength',               3),
    ('powerlifting', 'jumps',                  1),
    ('powerlifting', 'lower_body_plyometrics',  1),
    ('powerlifting', 'upper_body_plyometrics',  1),
    ('powerlifting', 'mobility',               2),
    ('weightlifting','strength',               3),
    ('weightlifting','jumps',                  2),
    ('weightlifting','lower_body_plyometrics',  2),
    ('weightlifting','upper_body_plyometrics',  1),
    ('weightlifting','mobility',               3),
    ('crossfit',     'strength',               3),
    ('crossfit',     'jumps',                  2),
    ('crossfit',     'lower_body_plyometrics',  2),
    ('crossfit',     'upper_body_plyometrics',  2),
    ('crossfit',     'mobility',               2),
    ('bodybuilding', 'strength',               3),
    ('bodybuilding', 'jumps',                  1),
    ('bodybuilding', 'lower_body_plyometrics',  1),
    ('bodybuilding', 'upper_body_plyometrics',  1),
    ('bodybuilding', 'mobility',               2),
    ('running',      'strength',               2),
    ('running',      'jumps',                  1),
    ('running',      'lower_body_plyometrics',  2),
    ('running',      'upper_body_plyometrics',  1),
    ('running',      'mobility',               3),
    ('cycling',      'strength',               2),
    ('cycling',      'jumps',                  1),
    ('cycling',      'lower_body_plyometrics',  1),
    ('cycling',      'upper_body_plyometrics',  1),
    ('cycling',      'mobility',               2),
    ('swimming',     'strength',               2),
    ('swimming',     'jumps',                  1),
    ('swimming',     'lower_body_plyometrics',  1),
    ('swimming',     'upper_body_plyometrics',  2),
    ('swimming',     'mobility',               3),
    ('triathlon',    'strength',               2),
    ('triathlon',    'jumps',                  1),
    ('triathlon',    'lower_body_plyometrics',  2),
    ('triathlon',    'upper_body_plyometrics',  1),
    ('triathlon',    'mobility',               3),
    ('tennis',       'strength',               2),
    ('tennis',       'jumps',                  2),
    ('tennis',       'lower_body_plyometrics',  2),
    ('tennis',       'upper_body_plyometrics',  3),
    ('tennis',       'mobility',               3),
    ('badminton',    'strength',               2),
    ('badminton',    'jumps',                  2),
    ('badminton',    'lower_body_plyometrics',  2),
    ('badminton',    'upper_body_plyometrics',  3),
    ('badminton',    'mobility',               3),
    ('squash',       'strength',               2),
    ('squash',       'jumps',                  2),
    ('squash',       'lower_body_plyometrics',  2),
    ('squash',       'upper_body_plyometrics',  3),
    ('squash',       'mobility',               3),
    ('gymnastics',   'strength',               3),
    ('gymnastics',   'jumps',                  3),
    ('gymnastics',   'lower_body_plyometrics',  3),
    ('gymnastics',   'upper_body_plyometrics',  3),
    ('gymnastics',   'mobility',               3),
    ('climbing',     'strength',               3),
    ('climbing',     'jumps',                  1),
    ('climbing',     'lower_body_plyometrics',  1),
    ('climbing',     'upper_body_plyometrics',  3),
    ('climbing',     'mobility',               3),
    ('other',        'strength',               2),
    ('other',        'jumps',                  1),
    ('other',        'lower_body_plyometrics',  1),
    ('other',        'upper_body_plyometrics',  1),
    ('other',        'mobility',               2)
) AS v(sport_slug, category_slug, relevance)
JOIN sports     s ON s.slug = v.sport_slug
JOIN categories c ON c.slug = v.category_slug
ON CONFLICT DO NOTHING;
